# create csr
---
- name: Role create_tls
  ansible.builtin.import_role:
    name: create_tls
  vars:
    backup: true
    tls_type: '{{ acme_account.tls_type | default(omit) }}'
    tls_curve: '{{ acme_account.tls_curve | default(omit) }}'
    tls_size: '{{ acme_account.tls_size | default(omit) }}'
    tls_digest: '{{ acme_account.tls_digest | default(omit) }}'
