# latest versions of app streams
# https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle
# RHEL 8.10 and RHEL 9.4
---
sv_app_default_versions:
  el8:
    default:
      python: '3.6'
    lts:
      perl: '5.26'
      python:
        - '3.6'
      php: '7.4'
      ruby: '2.5'
      # 以下は短い
      nodejs: '24' # 2028-04
      java:
        - '25' # latest
      dotnet:
        - '10.0' # 2028-11
    sts:
      perl: '5.32' # 2025-04
      python:
        - '3.12' # 2029-05 last
        - '3.11' # 2026-05
        # - '3.9' # 2025-11
        # - '3.8' # 2023-05
        # - '2.7' # 2024-06
      php: '8.2' # 2029-05 last
      ruby: '3.3' # 2027-03
      nodejs: '24' # 2028-04
      java:
        - '25' # latest
        - '21' # 2029-12
        - '17' # 2027-12
        # - '11' # 2024-10
        - '1.8.0' # 2026-05
      dotnet:
        - '10.0' # 2028-11
        - '9.0' # 2026-05
        - '8.0' # 2026-11
        # - '7.0' # 2024-05
        # - '6.0' # 2024-11
        # - '5.0' #2022-05
        # - '3.1' # 2022-12
        # - '3.0' # 2020-03
        # - '2.1' # 2021-08
      gcc:
        - '15' # 2028-11
        - '14' # 2026-11
        # - '13' # 2025-11
        # - '12' # 2024-11
        # - '11' # 2023-11
        # - '10' # 2022-11
        # - '9' # 2021-11
  el9:
    default:
      python: '3.9'
    lts:
      # TODO: 以下は短い
      nodejs: '24' # 2028-04
      java:
        - '25' # latest
      dotnet:
        - '10.0' # 2028-11
    sts:
      # perl: ''
      python:
        - '3.12' # 2027-04
        - '3.11' # 2026-05
        - '3.9' # full
      php: '8.3' # 2029-05
      ruby: '3.3' # 2027-03
      nodejs: '24' # 2028-04
      java:
        - '25' # latest
        - '21' # 2029-12
        - '17' # 2027-12
        # - '11' # 2024-10
        - '1.8.0' # 2026-05
      dotnet:
        - '10.0' # 2028-11
        - '9.0' # 2026-11
        - '8.0' # 2026-11
        # - '7.0' # 2024-05
        # - '6.0' # 2024-11
      gcc:
        - '15' # 2029-11
        - '14' # 2026-11
        - '13' # 2025-11
        - '12' # 2024-11
