- name: Task webuser
  ansible.builtin.import_tasks:
    file: webuser.yml

- name: Add webusers to webusers
  ansible.builtin.set_fact:
    user_webusers: >-
      {{ {user: user_webuser} | combine(user_webusers) }}
