# webusers
- name: Task list
  ansible.builtin.import_tasks:
    file: list.yml

- name: Set webusers to an empty dict
  ansible.builtin.set_fact:
    user_webusers: {}

- name: Load webuser
  ansible.builtin.include_tasks:
    file: load_webuser.yml
  loop: '{{ user_webuser_list }}'
  loop_control:
    loop_var: user
