- name: User webuser
  hosts:
    - ctl
  tasks:
    - name: Task webuser in user role
      ansible.builtin.import_role:
        name: user
        tasks_from: webuser
    - name: Debug user_webuser var
      ansible.builtin.debug:
        var: user_webuser
